
export const metadata = {
  title: "Taksha React",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body > 
      {children}</body>
    </html>
  );
}
